version: 2.1

orbs:
  kube: twdps/kube-ops@2.1.0
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@5.4.0

globals:
  - &context platform
  - &executor-image ghcr.io/twplatformlabs/circleci-eks-ops:alpine-2026.04.3

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        description: cluster and tf workspace name
        type: string
    steps:
      - op/env:
          env-file: op.<< parameters.cluster >>.env
      - kube/op-kubeconfig:
          op-value: platform/<< parameters.cluster>>/kubeconfig-base64

  integration-test:
    description: validate functional health of argocd-core implementation
    parameters:
      cluster:
        description: cluster and tf workspace name
        type: string
    steps:
      - run:
          name: run integration tests
          command: bash scripts/integration_test.sh << parameters.cluster >>

jobs:

  deploy argocd-core as configuration manager:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to be configured
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - run:
          name: deploy argocd-core
          command: bash scripts/install_argocd_core.sh << parameters.cluster >>
      - integration-test:
          cluster: << parameters.cluster >>

  set cluster role:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to be configured
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - run:
          name: set the cluster role - connecting to role definition in psk-aws-control-plane-configuration
          command: bash scripts/set_cluster_role.sh << parameters.cluster >>
      - run:
          name: vaidate cluster role application-root reports healthy
          command: bash scripts/validate_application_root.sh << parameters.cluster >>

  run-integration-test:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to be configured
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - integration-test:
          cluster: << parameters.cluster >>

workflows:

  set sandbox cluster role configuration management:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - deploy argocd-core as configuration manager:
          name: deploy sandbox cluster configuration manager
          context: *context
          cluster: sbx-i01-aws-us-east-1
          filters: *on-push-main

      - set cluster role:
          name: set role as sandbox
          context: *context
          cluster: sbx-i01-aws-us-east-1
          requires:
            - deploy sandbox cluster configuration manager
          filters: *on-push-main

  set production cluster role configuration management:
    jobs:
      - deploy argocd-core as configuration manager:
          name: deploy production cluster configuration manager
          context: *context
          cluster: prod-i01-aws-us-east-2
          filters: *on-tag-main

      - set cluster role:
          name: set role as production
          context: *context
          cluster: prod-i01-aws-us-east-2
          requires:
            - deploy production cluster configuration manager
          filters: *on-tag-main

      - do/gh-release:
          name: generate release notes
          context: *context
          notes-from-file: release.md
          include-commit-msg: true
          before-release:
            - op/env:
                env-file: op.prod-i01-aws-us-east-2.env
          requires:
            - set role as production
          filters: *on-tag-main

      - do/schedule-pipeline:
          name: schedule nightly integration tests
          context: *context
          scheduled-pipeline-name: nightly argocd core integration test
          scheduled-pipeline-description: |
            Automatically triggers nightly run of integration-test job
          hours-of-day: "[1]"
          days-of-week: "[\"SUN\"]"
          before-schedule:
            - op/env:
                env-file: op.prod-i01-aws-us-east-2.env
          filters: *on-tag-main

  run nightly integration test:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - run-integration-tests:
          name: nightly sbx-i01-aws-us-east-1 integration test
          cluster: sbx-i01-aws-us-east-1
          context: *context
      - run-integration-tests:
          name: nightly prod-i01-aws-us-east-2 integration test
          cluster: prod-i01-aws-us-east-2
          context: *context
