version: 2.1

orbs:
  kube: twdps/kube-ops@2.0.0
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@5.3.2

globals:
  - &context platform
  - &executor-image ghcr.io/twplatformlabs/circleci-eks-ops:alpine-2026.04.3

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        description: cluster and tf workspace name
        type: string
    steps:
      - op/env:
          env-file: op.<< parameters.cluster >>.env
      - kube/op-kubeconfig:
          op-value: platform/<< parameters.cluster>>/kubeconfig-base64
      - do/bash-functions

  integration-test:
    description: validate functional health of argocd-core implementation
    parameters:
      cluster:
        description: cluster and tf workspace name
        type: string
    steps:
      - run:
          name: run integration tests
          command: scripts/integration_test.sh << parameters.cluster >>

jobs:

  deploy argocd-core as configuration manager:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to be configured
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - run:
          name: deploy argocd-core
          command: scripts/install_argocd_core.sh << parameters.cluster >>
      - run:
          name: integration test for cluster configuration App definition
          command: scripts/integration_test.sh << parameters.cluster >>

  set cluster role:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to be configured
        type: string
      cluster-role:
        description: cluster role to be configured
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - run:
          name: set the cluster role - connecting to role definition in psk-aws-control-plane-configuration
          command: scripts/set_cluster_role.sh << parameters.cluster >> << parameters.cluster-role >>

workflows:

  set sandbox cluster role configuration management:
    jobs:
      - deploy argocd-core as configuration manager:
          context: *context
          cluster: sbx-i01-aws-us-east-1
          filters: *on-push-main

      - set cluster role:
          context: *context
          cluster: sbx-i01-aws-us-east-1
          cluster-role: sandbox
          requires:
            - deploy argocd-core as configuration manager
          filters: *on-push-main
