version: 2.1


orbs:
  kube: twdps/kube-ops@1.1.2
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@5.1.0

globals:
  - &context platform
  - &executor-image ghcr.io/twplatformlabs/circlece-eks-ops:alpine-2026.04.2

# on-push-main: &on-push-main
#   branches:
#     only: /main/
#   tags:
#     ignore: /.*/

# on-tag-main: &on-tag-main
#   branches:
#     ignore: /.*/
#   tags:
#     only: /.*/


commands:

  set-environment:

  

    scripts:

    install_argocd_core.sh   # installs core and sets the admin argo project definition
    set_cluster_role.sh      # defines the configuration repo core will use to manage this cluster based on role


jobs:

  deploy-argocd-code-dist-control-plane-config-manager:
    docker:
      - image: *executor-image
    parameters:
      cluster:
      cluster-role:
      steps:
        - checkout
        - set-environment:
        
  
      

workflows:

  deploy argocd core as on-cluster configuration manager:
    jobs:
      - deploy-argocd-code-dist-control-plane-config-manager:
          context: 
          cluster:
          cluster-role:
          executor-image: *executor-image

      - set-cluster-role:
          requires:
            - deploy-argocd-code-dist-control-plane-config-manager

